version: '3.8'

services:
  wine-api:
    build: .
    image: wine-classifier:latest
    container_name: wine-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped